import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import ProfileHeader from "@/Components/Profile/ProfileHeader";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Work Movie App",
    description: "Generated by create next app",
};

// not root layout this is main layout

export default function Layout({ children }) {
    return (
        <div className="min-h-screen w-full bg-cover bg-center object-cover bg-[url('/Images/Home/pages_bg.png')]">
            <ProfileHeader />
            <div className="">
                {children}
            </div>
        </div>
    );
}
